services:
   bytebot-desktop:
     volumes:
       - ./progress-data:/app/progress
     # Building locally with OpenCV 4.8.0 from Ubuntu 24.04

   bytebot-agent:
     # Building locally with OpenCV 4.8.0 from Ubuntu 24.04
     volumes:
       - ./progress-data:/app/progress
     # Enhanced OpenCV 4.8.0 capabilities with ML and morphology support
