# Docker Compose Override - Cross-Platform Optimizations
# This file is automatically loaded by Docker Compose.
#
# 1. Force x86_64 Architecture
#    - Ensures consistent builds across Mac (Apple Silicon), Linux, and Windows
#    - On Apple Silicon: Uses Rosetta 2 emulation (~20% slower but stable)
#    - On x86_64 systems: Native performance, no emulation
#    - Benefits: Consistent OpenCV binaries, no platform-specific build issues
#
# 2. GPU Configuration for OmniParser
#    - Automatically enables NVIDIA GPU if nvidia-container-toolkit is installed
#    - Falls back to CPU if GPU not available (no errors)
#    - Apple Silicon: GPU config ignored (no NVIDIA support)

services:
  bytebot-agent:
    platform: linux/amd64

  bytebot-desktop:
    platform: linux/amd64

  bytebot-ui:
    platform: linux/amd64

  bytebot-omniparser:
    platform: linux/amd64
    # GPU support: Requires nvidia-container-toolkit on host
    # If not available, Docker ignores this and falls back to CPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  bytebot-llm-proxy:
    platform: linux/amd64
